---
title: "Atuação na tramitação das proposições"
output:
  html_document:
    theme: paper
    css: styles.css
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  # message = FALSE,
  # warning = FALSE,
  # fig.cap = '',
  # fig.align = 'center',
  fig.width = 6,
  fig.height = 5
)

Sys.setenv(LANGUAGE="pt-br")
Sys.setlocale("LC_TIME", "pt_BR")
options(scipen = 999)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(reactable)
library(ggchicklet)
library(ggbeeswarm)
library(hrbrthemes)
theme_set(theme_ipsum_rc())

source(here::here("code/read_ready.R"))
```

<!-- TO DO incluir parlamentares com zero ações -->

```{r}
proposicoes = read_proposicoes()
detalhes_atuacao = read_atuacao()
resumo_atuacao = detalhes_atuacao %>%
  filter(!is.na(nome_autor), !(tipo_acao %in% c("Outros", "Recurso", "Parecer"))) %>% 
  group_by(casa,
           nome_autor,
           partido,
           uf,
           governismo,
           peso_politico,
           tipo_generico) %>%
  summarise(acoes = sum(num_documentos), 
            .groups = "drop")
```

<!-- Considerando e ignorando proposições apensadas -->

```{r fig.height=8, fig.width=8}
resumo_atuacao  %>%
  group_by(casa) %>% 
  filter(acoes >= 5 | casa == "senado") %>%
  ggplot(aes(
    x = reorder(nome_autor, acoes, sum),
    y = acoes,
    fill = tipo_generico
  )) +
  facet_grid(casa ~ ., scales = "free") +
  geom_chicklet() +
  coord_flip() +
  scale_fill_brewer(palette = "Accent") +
  labs(
    x = "",
    y = "Açòes",
    fill = "Tipo da ação",
    title = "Parlamentares mais atuantes"
  )
```

```{r}
resumo_atuacao %>% 
  group_by(casa,
           nome_autor,
           partido,
           uf,
           governismo,
           peso_politico) %>% 
  summarise(acoes = sum(acoes), 
            .groups = "drop") %>% 
  ggplot(aes(x = governismo, y = acoes)) + 
  geom_point(size = 1.8, alpha = .6, color = "brown") + 
  labs(
    title = "Correlação entre governismo e atuação nas PDLs", 
    subtitle = "Parlamentares de oposição atuaram mais", 
    y = "Ações", 
    x = "Governismo (neg. significa oposição)"
  )
  
```


